language: node_js
node_js:
  - "0.10"

branches:
  only:
    - develop
    - master
    - /^test/.*$/
    - /^v\d+\.\d+\.\d+(-.+)?$/

before_install:
  - npm install -g gulp-cli
  - npm install -g bower

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start
  - webdriver-manager start > /dev/null &
  - sleep 1 # give webdriver time to start

script:
  - gulp test
  - gulp inject --protractor
  - node_modules/.bin/protractor src/e2e-test/protractor.conf.js --browser=firefox

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/18575ac051d21e4340b1
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
