language: node_js
node_js:
  - '5.4'
branches:
  only:
    - develop
    - master
    - blob
    - '/^test/.*$/'
    - "/^v\\d+\\.\\d+\\.\\d+(-.+)?$/"
before_install:
  - npm install -g gulp-cli
  - npm install -g bower
  - npm install -g azure-cli
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - 'npm start > /dev/null &'
  - npm run update-webdriver
  - sleep 1
  - 'webdriver-manager start > /dev/null &'
  - sleep 1
script:
  - gulp test
  - gulp inject --protractor
  - node_modules/.bin/protractor src/e2e-test/protractor.conf.js --browser=firefox
notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/18575ac051d21e4340b1'
    on_success: always
    on_failure: always
    on_start: false
env:
  global:
    - secure: "i6434wZBSlUMqCFyVu7ytbJa3IjmfwB5h3FrqejzL/nnUEYOw7KMPy8ZqV3mWhQ2PTWVA7rmKP/SZ4wKSeNWEAuSgVRNik3dX/nCVBX8Dn7HiKn9G9BjQUHbUEcDMKE5cWz86/IVcK2OMKHFBb2GOArqN0NrPFf2Pv+TyorAtkoamXyIo57nBB31Cqok9sl0pz1a4Ft1X6fxRKh8Rr5zU4++Nh4+Ur0awvsecHSb7O9vNpk23DXaiBzwZUhxKIL3aFgVMFCt9f/ComTtB9ZhnZTxMj7epgu4StYa4uOqdwWo9nCKg1egz9SJNmVelkUgmSinC4jM3NiOEOVpWJRuZynESWlgBndZb5z782o/XSWacJjRZVDlc9m8EaowaC+gezl67dhGPP5hv6zXzQTtL3zpj4p1VTJqpps+k003PB76ASkfJQKOVS5nqgshy2RXDlpbp/l9S9Q5LFvltVZjvYfmeMqBlkzgYeKtzGLm/RM89UYOzgU2qzFSu1Ku1y41d/y0HPCHf4iOPxfJt0MwAa/KEEwZF1cKMXeIPvFmRt3TT2cQLzg2DNmneph3Iv0nUxSBvmLmj6BYGby9xnOkMUrlPkx/Ui0heQBReRjy447eAHO4qLsQn0LVhy3AMskgv+uxYhIdVGW36QbIf8HBlM9kkY30lAVizoufphwwAoA="
    - secure: XYD54RdMT3yY9YuI7nk8J8sSRG/eQ/FK2U4W+dRmnBVls4mwZamxX1oThOVjoyV8VydBiSC0RB1+EKl4DbtHcABC0kZmfQEKhupNaVVB1JB/7BDN1w2W4Iqdy0KH3M3aX0qwVQiIieyuW5yzWxUTxJRk7JlxT2H/ogmGt0nuBwncD5ZPDYMbyMChOJL58iT8KJcAUZ+WZxFKgseh/BufQajhVaq91cSbzHRY8Yd/MmBTPVvUYkKIPbbwcwORcoqg4rXgN8LQ414yGP14HbVgY/tCO10nvXgQoLq1Jlyy61vPHw+NIhRr5KRs8JohsgHanGZE3lTPdJAEU8+ynmU0YbBM2yn4SBF9x1Mz3q6dz92SGw4eIirb4PJV/ChLjkom0+ZRb8EDHPOxgC7j0nPqj0hEAk6B/nasYqGFAfiEA1LXMV8PE0QNaCM2zLY2xPV2IpWMvatKt5rZFWBrQEjvmfs5x9E5n4ZuS10W+DCTxMr1Wj0RJTfInM4SZX1PFrWkT14gsdv7B2O3At6pXEsrleiPMSQvjgJsNevU8gzq0/yWtFMIdEJ2IAV/aMRkMG6GfesZc0JKtL/2B14vQUWSw5Lg1/tpcNSbHctfbRDyOxXYBfJpbB6WEg5cd8hloS3ekeKozuG112gFGY+ht89NG/8qWJI008PG34n9ApimCB0=
    - secure: eIuWMh5oHKFqKBqGBSRej3o3eym23kftKwxSrn3iG6/M0mC4gmTxzs0RnV1SoiHLhDOW47QmFebi66ssPP64R464e9hdS51ZloP0tTJ5KRHFXFdBjzPauzizGfmmOc2nDdK/4PmW/WK/FoflvIaZnMaSj8RCUbF/hIC6Pqa7GgX827hy/Biugph8hnkrkr9hp+qnScFdE2k0D9ZuHWsv7isvZ+dQuUPJ4z/DfmtE0JuQphO2fHB/fmTx6ms1/6JhgkRW+cluZ56LmGIWDBplrIDV3vmJ9ivatgkhZN7ohieLlEMPHJePsVVoMYKrAo/yqOR+aUw+Tqt5u3GMITlTsvYugQb401RVzGtiKbVmFN2hLZR2oKA16Y7yCU+/SMad+xTMV0152+n1bwiMTYGms1/g2EjorJbuVV7fqBgbfRrsFlFiq0EAVzBG8YX++nF38TEUR1+SQm5aTfJFMcETNM1x6/SqP0ERzMtSaZDzu0NpOi5QoAwQ+Lp0eZdl+ATetUWlgTwHL/VFptmh5sR5ubd1RdQiMGWOWHQTmrvFqJuUTV89vfUETlBZT4AP7Re+Eq9dC6ZSxYU1O2SWqEWsVQiwsPEl5WXUsYicqvArrHCQZaadRUw91l1kCTz98xE9L5HxFLadBYcoHL2gqkTDOrrhdi0+AJhD5rfXCe3iXWs=
after_success:
  - gulp clean
  - gulp inject
  - source devdeploy.sh
