language: node_js
node_js:
  - "0.10"

branches:
  only:
    - develop
    - master
    - /^test/.*$/
    - /^v\d+\.\d+\.\d+(-.+)?$/

before_install: 
  - npm install -g gulp-cli
  - npm install -g bower

script:
  - gulp test
