language: node_js
node_js:
- '5.4'
branches:
  only:
  - develop
  - master
  - /.+/
  - /^test/.*$/
  - /^v\d+\.\d+\.\d+(-.+)?$/
before_install:
- npm install -g gulp-cli
- npm install -g bower
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm start > /dev/null &
- npm run update-webdriver
- sleep 1
- webdriver-manager start > /dev/null &
- sleep 1
script:
- gulp test
- gulp inject --protractor
- node_modules/.bin/protractor src/e2e-test/protractor.conf.js --browser=firefox
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/18575ac051d21e4340b1
    on_success: always
    on_failure: always
    on_start: false
env:
  global:
  - CXX=g++-4.8
  - secure: A5a0+y9I6Z471wluD5Ty2U2ciUoXI8GZovPtMeABbZ1jrmTmcyvmbXVOHTRE/YXjRWMMjV5YqKIAvA32ftJghFOzM2ugLWloEPvywOQ2UwDBHkHPytayZKxNqTE2LGNo1hnDhGBQKlaT7jm/aY/JraSyirpDPgmXVtsQsIKaeFB4maYaf0p+DIXYrwSz8CM3rgj6Huq9rjC9BNUD17A94QkNgmQGvmckJ2N13QMnb/w3xkHzyMhQbKsqCRQiB9sDnGy39dSqgdQJACenygm9yhMJ9eFVSTuYRmNdPcJsvJZUyWP83FAaFK6uNfpcmfu4Q6msaLCzLFNmSwhrwC1vnx8JwXZ7SEp8q/FtH1BSAedze3D7ytc9Ap7gZjPbn+cJr575w5cOKIiI7n1LkYuaLFsErU0+AINjQb2NH2al5vBvb/B4UVx3YBQtSGecjjZa8RcXsLSgj/kcGwKCWq0DNcwYSL/FcpBT17TKqU9cBeIfM0MZliemq7YirfIpr88AElluNR7N7V4kJzX+TZ6+5o+NhhrNCkJOzqnKTrtG/3YCoYRXtwkMK6fz9TgNnWAlJiOF4vcUG1rudnx35x8rD7H77R8r8pzpekcyn8XF50QTYVjH/GhSDQ0pFiCjoNM4BOXRw+WDEYYhKy8dbROPilEEUfVPKHKE2MxBi1S3rpQ=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
after_success:
- gulp clean
- gulp inject
- source devdeploy.sh
